import pandas as pd

def compute_total_revenue(csv_file):
    # Read the CSV file into a pandas DataFrame
    df = pd.read_csv(csv_file)
    
    # Compute the total revenue by grouping the data by product and summing the revenue column
    total_revenue = df.groupby('product_name')['product_price'].sum()
    
    # Return the total revenue by product
    return total_revenue

# Example usage
csv_file = 'customerorders.csv'  # Path to your CSV file

total_revenue = compute_total_revenue(csv_file)
print("Compute the total revenue generated by each product in the dataset.")
# Print the total revenue by product
print(total_revenue)

print()
print("Compute the total revenue generated by each customer in the dataset.")
print()
df = pd.read_csv(csv_file)
total_revenue1 = df.groupby('customer_id')['product_price'].sum()
# Print the total revenue by product
print(total_revenue1)
print()
n = 7
sorted_customers = total_revenue1.sort_values(ascending=False)
total_revenue2 = sorted_customers.head(n)
print("Identify the top 10 customers by revenue generated.")
print(total_revenue2)

